const LIST_LESSON_ASTRONOMY = [
   {
      id: 1,
      locked: false,
      subject_id: 2,
      title: "Matahari",
      slug: "matahari",
      desc: "Matahari adalah bintang pusat tata surya yang menjadi sumber utama cahaya dan energi bagi planet-planet di sekitarnya.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/model/sun.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-sun.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-sun.mp3",
      created_at: "2025-10-21T15:59:16.839Z",
   },
   {
      id: 2,
      locked: false,
      subject_id: 2,
      title: "Merkurius",
      slug: "merkurius",
      desc: "Merkurius adalah planet terdekat dari Matahari dan memiliki permukaan berbatu serta suhu ekstrem.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/mercury.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-mercury.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-mercury.mp3",
      created_at: "2025-10-21T16:00:00.000Z",
   },
   {
      id: 3,
      locked: false,
      subject_id: 2,
      title: "Venus",
      slug: "venus",
      desc: "Venus dikenal sebagai planet paling panas di tata surya dengan atmosfer tebal yang kaya karbon dioksida.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/venus.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-venus.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-venus.mp3",
      created_at: "2025-10-21T16:01:00.000Z",
   },
   {
      id: 4,
      locked: false,
      subject_id: 2,
      title: "Bumi",
      slug: "bumi",
      desc: "Bumi adalah satu-satunya planet yang diketahui mendukung kehidupan, dengan atmosfer kaya oksigen dan air dalam bentuk cair.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/earth.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-earth.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-earth.mp3",
      created_at: "2025-10-21T16:02:00.000Z",
   },
   {
      id: 5,
      locked: false,
      subject_id: 2,
      title: "Mars",
      slug: "mars",
      desc: "Mars dijuluki 'planet merah' karena warnanya yang kemerahan akibat oksidasi besi di permukaannya.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/mars.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-mars.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-mars.mp3",
      created_at: "2025-10-21T16:03:00.000Z",
   },
   {
      id: 6,
      locked: false,
      subject_id: 2,
      title: "Jupiter",
      slug: "jupiter",
      desc: "Jupiter adalah planet terbesar di tata surya, terkenal dengan Bintik Merah Besar yang merupakan badai raksasa.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/jupiter.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-jupiter.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-jupiter.mp3",
      created_at: "2025-10-21T16:04:00.000Z",
   },
   {
      id: 7,
      locked: true,
      subject_id: 2,
      title: "Saturnus",
      slug: "saturnus",
      desc: "Saturnus terkenal dengan cincin indah yang tersusun dari es dan batu berukuran kecil hingga besar.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/saturn.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-saturn.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-saturn.mp3",
      created_at: "2025-10-21T16:05:00.000Z",
   },
   {
      id: 8,
      locked: true,
      subject_id: 2,
      title: "Uranus",
      slug: "uranus",
      desc: "Uranus memiliki rotasi unik yang miring hampir 98 derajat, sehingga tampak berguling saat mengelilingi Matahari.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/uranus.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-uranus.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-uranus.mp3",
      created_at: "2025-10-21T16:06:00.000Z",
   },
   {
      id: 9,
      locked: true,
      subject_id: 2,
      title: "Neptunus",
      slug: "neptunus",
      desc: "Neptunus merupakan planet terjauh dari Matahari dan memiliki angin tercepat di tata surya.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/neptune.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-neptune.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-neptune.mp3",
      created_at: "2025-10-21T16:07:00.000Z",
   },
   {
      id: 10,
      locked: true,
      subject_id: 2,
      title: "Pluto",
      slug: "pluto",
      desc: "Pluto dulunya dianggap planet kesembilan, namun kini diklasifikasikan sebagai planet kerdil di Sabuk Kuiper.",
      model_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/pluto.glb",
      marker_img_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/marker-pluto.png",
      audio_url: "https://cdn.jsdelivr.net/gh/badzlan/ar-system/audio-pluto.mp3",
      created_at: "2025-10-21T16:08:00.000Z",
   },
];

export { LIST_LESSON_ASTRONOMY };
